bot_token: "YOUR_BOT_TOKEN"
notifiers: []
  # - on: []
  #   # - "EVENT_OCCURRENCE"
  #   # - "EVENT_REMINDER"
  #   actions: []
  #     #- type: "embed"
  #     #  mention: 1106256722923880468
  #     #  channel: 1149040761342537909
  # - on: []
  #     #- "EVENT_CREATION"
  #     #- "EVENT_CHANGE"
  #     #- "EVENT_CANCELLATION"
  #     #- "EVENT_RESPONSE"
  #   actions: []
  #     # - type: "embed"
  #     #   mention: 1106256722923880468
  #     #   channel: 1149040761342537909
google_calendar_credentials:
  client_id: "GCLOUD_CLIENT_ID"
  client_secret: "GCLOUD_CLIENT_SECRET"
